// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ0_vjIM_Qx2AcK27CvseJC8PLvFMj_fU',
    appId: '1:608612419819:android:d9c1370875636eded716ae',
    messagingSenderId: '608612419819',
    projectId: 'symmetry-test-52eeb',
    storageBucket: 'symmetry-test-52eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6OYmDM_j2nG6VonPIFPVGJbhe1Cb8ng',
    appId: '1:608612419819:ios:6b9522e637db1554d716ae',
    messagingSenderId: '608612419819',
    projectId: 'symmetry-test-52eeb',
    storageBucket: 'symmetry-test-52eeb.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0_vjIM_Qx2AcK27CvseJC8PLvFMj_fU',
    appId: '1:608612419819:web:web-app-placeholder',
    messagingSenderId: '608612419819',
    projectId: 'symmetry-test-52eeb',
    authDomain: 'symmetry-test-52eeb.firebaseapp.com',
    storageBucket: 'symmetry-test-52eeb.firebasestorage.app',
  );
}
